[build]
  publish = "public"
  command = "echo 'Static site ready'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/auth/callback"
  to = "/auth/callback.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 