[build]
  publish = "public"
  functions = "netlify/functions"
  command = "echo 'Static site with functions ready'"

[build.environment]
  NODE_VERSION = "18"

# Netlify Functions
[functions]
  node_bundler = "esbuild"

# Redirects for OAuth and API routes
[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/auth/callback"
  to = "/.netlify/functions/callback"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/set-threshold"
  to = "/.netlify/functions/set-threshold"
  status = 200

[[redirects]]
  from = "/get-threshold"
  to = "/.netlify/functions/get-threshold"
  status = 200

[[redirects]]
  from = "/debug-threshold"
  to = "/.netlify/functions/debug-threshold"
  status = 200

[[redirects]]
  from = "/store-token"
  to = "/.netlify/functions/store-token"
  status = 200

[[redirects]]
  from = "/get-shop-token"
  to = "/.netlify/functions/get-shop-token"
  status = 200

# Main app route
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Fallback for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 