# This file stores configuration for your Shopify app.

client_id = "6d06fe10e07175aeba07d7225e48f3b1"
name = "quantity-validation-app"
application_url = "https://your-app-name.netlify.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[access_scopes]
scopes = "write_products,read_products"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://your-app-name.netlify.app/auth/callback"
]

[webhooks]
api_version = "2025-07"

[pos]
embedded = false
